name: qwitravel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  i18n: ^4.1.0
  i18n_extension: ^10.0.2
  material_color_utilities: ^0.5.0
  provider: ^6.1.1
  sqflite_common: ^2.5.3
  sqflite_common_ffi: ^2.3.2
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
